project:
  type: website

website:
  title: "Quantitative Environmental Services"
  site-url: "https://www.envirostats.ca"
  open-graph: true
  page-footer: "Copyright 2025, EnviroStats Solutions Inc."
  navbar:
    right:
      - href: index.qmd
        text: Home
      - mission.qmd
      - services.qmd
      - about.qmd
      - posts.qmd
    logo: images/favicon.png
  favicon: images/favicon.png

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    email-obfuscation: javascript

editor: source


